GET http://127.0.0.1:8000/api/currencies
Accept: application/json

###

POST http://127.0.0.1:8000/api/currencies
Content-Type: application/json
Accept: application/json

{
    "code": "EUR",
    "name": "Euro",
    "rate": 42.50
}

###

GET http://127.0.0.1:8000/api/currencies/1
Accept: application/json

###

PATCH http://127.0.0.1:8000/api/currencies/1
Content-Type: application/json
Accept: application/json

{
    "rate": 43.15
}

###

DELETE http://127.0.0.1:8000/api/currencies/1
Accept: application/json
